before:
  hooks:
  - go mod download
  - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  - arm
  goarm:
  - 7
  dir: .
  main: .
  flags:
  - -trimpath
  ldflags:
  - -s -w -X github.com/den-is/ktempl/cmd.version={{.Version}} -X github.com/den-is/ktempl/cmd.commit={{.Commit}} -X github.com/den-is/ktempl/cmd.date={{.Date}}
archives:
- name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  wrap_in_directory: true
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  files:
  - LICENSE
  - README.md
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-snapshot-{{ .ShortCommit }}"
release:
  draft: true
  prerelease: false
changelog:
  filters:
    exclude:
    - "^docs:"
    - "^test:"
    - "^readme|README"
    - "^roadmap|ROADMAP"
    - "^gorelease"
