before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    dir: .
    main: .
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/den-is/ktempl/cmd.version={{.Version}} -X github.com/den-is/ktempl/cmd.commit={{.Commit}} -X github.com/den-is/ktempl/cmd.date={{.Date}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format: tar.gz
    wrap_in_directory: true
    rlcp: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-snapshot-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^readme|README"
      - "^roadmap|ROADMAP"
      - "^gorelease"
      - "^cicd"
      - "^typo"
      - "^gitignore"
